export interface UserTypes {
  id: number;
  name: string;
  slug: string;
  email: string;
  user_type: string;
  position: string;
  kvkk_approved: boolean;
  membership_approved: boolean;
  created_at: Date;
  updated_at: Date | string;
  city: string;
  district: string;
  register_code: string;
  roles: string[];
  phone: string;
  image: string;
  notification_count: number;
  message_count: number;
};
