export interface UserTypes {
  id: number;
  name: string;
  email: string;
  user_type: string;
  phone: string;
  phone_code: string;
  phone_number: string;
  birth_date: string | null;
  age: number | null;
  gender: string | null;
  address: string | null;
  city: string | null;
  country: string;
  timezone: string;
  currency: string;
  photo: string | null;
  is_active: boolean;
  created_at: Date;
  updated_at: Date | string;
};